/**
 * Presentation Framework Core — Executive Template Library (ADR-001)
 *
 * 10 Pre-loaded Executive Templates with metadata versioning.
 * UI-Agnostic data structures consuming Framework Widgets.
 */

import { SlideTemplate } from './types';

export const EXECUTIVE_TEMPLATES: SlideTemplate[] = [
  {
    id: 'template_ranking_clientes',
    name: 'Ranking de Clientes',
    version: '1.0.0',
    description: 'Visualização dos principais clientes por faturamento e volume.',
    category: 'Comercial',
    layout: '2col',
    widgets: [
      {
        id: 'w_ranking_clientes_1',
        type: 'ranking',
        title: 'Top Clientes por Faturamento',
        indicators: ['faturamento'],
      },
      {
        id: 'w_ranking_clientes_2',
        type: 'table',
        title: 'Detalhamento dos Clientes',
        indicators: ['faturamento', 'volume'],
      },
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
    author: 'Sistema Coffee++',
    origin: 'system',
  },
  {
    id: 'template_evolucao_mensal',
    name: 'Evolução Mensal',
    version: '1.0.0',
    description: 'Acompanhamento da curva mensal de faturamento e metas.',
    category: 'Vendas',
    layout: 'dashboard',
    widgets: [
      {
        id: 'w_evolucao_1',
        type: 'kpi_card',
        title: 'Resumo da Performance',
        indicators: ['faturamento', 'volume', 'investimento'],
      },
      {
        id: 'w_evolucao_2',
        type: 'line_chart',
        title: 'Tendência do Faturamento Mensal',
        indicators: ['faturamento'],
      },
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
    author: 'Sistema Coffee++',
    origin: 'system',
  },
  {
    id: 'template_mix_familia',
    name: 'Mix por Família',
    version: '1.0.0',
    description: 'Distribuição de vendas e volumes entre as famílias de produtos.',
    category: 'Produtos',
    layout: '2col',
    widgets: [
      {
        id: 'w_mix_1',
        type: 'bar_chart',
        title: 'Volume por Família de Produtos',
        indicators: ['mix', 'volume'],
      },
      {
        id: 'w_mix_2',
        type: 'table',
        title: 'Tabela de Famílias',
        indicators: ['volume', 'preco_medio'],
      },
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
    author: 'Sistema Coffee++',
    origin: 'system',
  },
  {
    id: 'template_rentabilidade',
    name: 'Rentabilidade',
    version: '1.0.0',
    description: 'Análise de receita, margens e investimento comercial.',
    category: 'Financeiro',
    layout: '2col',
    widgets: [
      {
        id: 'w_rent_1',
        type: 'kpi_card',
        title: 'Indicadores de Margem',
        indicators: ['margem', 'faturamento', 'investimento'],
      },
      {
        id: 'w_rent_2',
        type: 'bar_chart',
        title: 'Faturamento vs Investimento',
        indicators: ['faturamento', 'investimento'],
      },
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
    author: 'Sistema Coffee++',
    origin: 'system',
  },
  {
    id: 'template_investimentos',
    name: 'Investimentos',
    version: '1.0.0',
    description: 'Monitoramento da verba comercial e taxa de investimento.',
    category: 'Trade',
    layout: 'full',
    widgets: [
      {
        id: 'w_inv_1',
        type: 'kpi_card',
        title: 'Taxa de Investimento Comercial',
        indicators: ['investimento'],
      },
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
    author: 'Sistema Coffee++',
    origin: 'system',
  },
  {
    id: 'template_top_produtos',
    name: 'Top Produtos',
    version: '1.0.0',
    description: 'Ranking dos SKUs mais vendidos.',
    category: 'Produtos',
    layout: '2col',
    widgets: [
      {
        id: 'w_top_prod_1',
        type: 'ranking',
        title: 'Top SKUs por Volume',
        indicators: ['sku', 'volume'],
      },
      {
        id: 'w_top_prod_2',
        type: 'bar_chart',
        title: 'Volume dos Principais Produtos',
        indicators: ['volume'],
      },
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
    author: 'Sistema Coffee++',
    origin: 'system',
  },
  {
    id: 'template_top_redes',
    name: 'Top Redes',
    version: '1.0.0',
    description: 'Desempenho das principais redes comerciais.',
    category: 'Comercial',
    layout: '2col',
    widgets: [
      {
        id: 'w_top_redes_1',
        type: 'table',
        title: 'Matriz de Redes',
        indicators: ['faturamento', 'volume'],
      },
      {
        id: 'w_top_redes_2',
        type: 'ranking',
        title: 'Ranking de Redes por Faturamento',
        indicators: ['faturamento'],
      },
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
    author: 'Sistema Coffee++',
    origin: 'system',
  },
  {
    id: 'template_participacao_canal',
    name: 'Participação por Canal',
    version: '1.0.0',
    description: 'Distribuição de faturamento entre canais de vendas.',
    category: 'Canais',
    layout: '2col',
    widgets: [
      {
        id: 'w_canal_1',
        type: 'bar_chart',
        title: 'Faturamento por Canal',
        indicators: ['canal', 'faturamento'],
      },
      {
        id: 'w_canal_2',
        type: 'table',
        title: 'Resumo por Canal',
        indicators: ['canal', 'faturamento', 'volume'],
      },
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
    author: 'Sistema Coffee++',
    origin: 'system',
  },
  {
    id: 'template_comparativo_regional',
    name: 'Comparativo Regional',
    version: '1.0.0',
    description: 'Análise do faturamento e volume por regiões.',
    category: 'Regional',
    layout: '2col',
    widgets: [
      {
        id: 'w_reg_1',
        type: 'bar_chart',
        title: 'Faturamento Regional',
        indicators: ['regiao', 'faturamento'],
      },
      {
        id: 'w_reg_2',
        type: 'kpi_card',
        title: 'Indicadores Regionais',
        indicators: ['regiao', 'faturamento'],
      },
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
    author: 'Sistema Coffee++',
    origin: 'system',
  },
  {
    id: 'template_dashboard_executivo',
    name: 'Dashboard Executivo',
    version: '1.0.0',
    description: 'Visão holística com KPIs, Gráficos, Ranking e Tabelas.',
    category: 'Executivo',
    layout: 'dashboard',
    widgets: [
      {
        id: 'w_dash_1',
        type: 'kpi_card',
        title: 'KPIs Principais',
        indicators: ['faturamento', 'volume', 'investimento'],
      },
      {
        id: 'w_dash_2',
        type: 'bar_chart',
        title: 'Evolução do Faturamento',
        indicators: ['faturamento'],
      },
      {
        id: 'w_dash_3',
        type: 'ranking',
        title: 'Ranking de Famílias',
        indicators: ['familia', 'volume'],
      },
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
    author: 'Sistema Coffee++',
    origin: 'system',
  },
];
