-- ==============================================================================
-- Migration: 20260910_create_cm_metas_futuras_rede.sql
-- Description: Módulo Metas por Rede — Nova Modalidade: Meta Futura
-- Governance: Tabela 100% isolada para projeções internas de faturamento futuro.
--             Isolamento absoluto de public.targets, cm_weekly_projections e RPS.
-- ==============================================================================

-- 1. Criar tabela canônica cm_metas_futuras_rede
CREATE TABLE IF NOT EXISTS public.cm_metas_futuras_rede (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager text NOT NULL,
    manager_id text NOT NULL,
    codigo_matriz text NOT NULL,
    rede text NOT NULL,
    canal text NOT NULL DEFAULT 'KA',
    target_year integer NOT NULL CHECK (target_year >= 2025 AND target_year <= 2035),
    target_month integer NOT NULL CHECK (target_month BETWEEN 1 AND 12),
    valor_planejado numeric(15,2) NOT NULL DEFAULT 0.00 CHECK (valor_planejado >= 0),
    created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT uq_cm_metas_futuras_rede UNIQUE (manager_id, codigo_matriz, rede, target_year, target_month)
);

-- 2. Índices de alta performance para busca por período e gerente
CREATE INDEX IF NOT EXISTS idx_cm_metas_futuras_periodo
ON public.cm_metas_futuras_rede (target_year, target_month);

CREATE INDEX IF NOT EXISTS idx_cm_metas_futuras_lookup 
ON public.cm_metas_futuras_rede (manager_id, target_year, target_month);

CREATE INDEX IF NOT EXISTS idx_cm_metas_futuras_rede_nome
ON public.cm_metas_futuras_rede (rede, target_year, target_month);

-- 3. Habilitar RLS
ALTER TABLE public.cm_metas_futuras_rede ENABLE ROW LEVEL SECURITY;

-- 4. Remover políticas residuais caso existam
DROP POLICY IF EXISTS "cm_metas_futuras_rede_select" ON public.cm_metas_futuras_rede;
DROP POLICY IF EXISTS "cm_metas_futuras_rede_write" ON public.cm_metas_futuras_rede;

-- 5. Políticas RLS para usuários autenticados e aprovados
CREATE POLICY "cm_metas_futuras_rede_select"
ON public.cm_metas_futuras_rede 
FOR SELECT 
TO authenticated
USING (
    auth.uid() IN (
        SELECT id FROM public.cm_user_profiles WHERE approved = true
    )
);

CREATE POLICY "cm_metas_futuras_rede_write"
ON public.cm_metas_futuras_rede 
FOR ALL 
TO authenticated
USING (
    auth.uid() IN (
        SELECT id FROM public.cm_user_profiles WHERE approved = true
    )
)
WITH CHECK (
    auth.uid() IN (
        SELECT id FROM public.cm_user_profiles WHERE approved = true
    )
);

-- 6. Grants
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cm_metas_futuras_rede TO authenticated;
GRANT SELECT ON public.cm_metas_futuras_rede TO anon;

COMMENT ON TABLE public.cm_metas_futuras_rede IS 'Projeções internas de faturamento futuro por rede (Meta Futura) — Isolado da RPS e Targets oficiais.';
COMMENT ON COLUMN public.cm_metas_futuras_rede.valor_planejado IS 'Valor planejado futuro em R$';
