-- ==============================================================================
-- Migration: 20260829_b5_4_company_targets_migration.sql
-- Description: B.5.4 — Migração controlada de ceo_targets para cm_company_targets
-- Governance: Preserva ceo_targets como fallback durante homologação.
-- ==============================================================================

-- 1. Criar tabela canônica cm_company_targets
CREATE TABLE IF NOT EXISTS public.cm_company_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year integer NOT NULL CHECK (year >= 2020 AND year <= 2050),
    month integer NOT NULL CHECK (month BETWEEN 1 AND 12),
    channel text NOT NULL DEFAULT 'Todos',
    target_forecast numeric(15,2) NOT NULL DEFAULT 0.00,
    target_internal numeric(15,2) NOT NULL DEFAULT 0.00,
    target_forecast_qty numeric(15,2) NOT NULL DEFAULT 0.00,
    target_internal_qty numeric(15,2) NOT NULL DEFAULT 0.00,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT uq_cm_company_targets_period_channel UNIQUE (year, month, channel)
);

-- 2. Habilitar RLS
ALTER TABLE public.cm_company_targets ENABLE ROW LEVEL SECURITY;

-- 3. Remover policies residuais caso existam
DROP POLICY IF EXISTS "cm_company_targets_select_auth" ON public.cm_company_targets;
DROP POLICY IF EXISTS "cm_company_targets_insert_auth" ON public.cm_company_targets;
DROP POLICY IF EXISTS "cm_company_targets_update_auth" ON public.cm_company_targets;
DROP POLICY IF EXISTS "cm_company_targets_delete_auth" ON public.cm_company_targets;

-- 4. Criar políticas RLS granulares
CREATE POLICY "cm_company_targets_select_auth" 
ON public.cm_company_targets 
FOR SELECT 
TO authenticated 
USING (
    auth.uid() IN (
        SELECT id FROM public.cm_user_profiles WHERE approved = true
    )
);

CREATE POLICY "cm_company_targets_insert_auth" 
ON public.cm_company_targets 
FOR INSERT 
TO authenticated 
WITH CHECK (
    auth.uid() IN (
        SELECT id FROM public.cm_user_profiles 
        WHERE approved = true AND role = ANY(ARRAY['Admin'::text, 'Admin Master'::text, 'CEO'::text])
    )
);

CREATE POLICY "cm_company_targets_update_auth" 
ON public.cm_company_targets 
FOR UPDATE 
TO authenticated 
USING (
    auth.uid() IN (
        SELECT id FROM public.cm_user_profiles 
        WHERE approved = true AND role = ANY(ARRAY['Admin'::text, 'Admin Master'::text, 'CEO'::text])
    )
)
WITH CHECK (
    auth.uid() IN (
        SELECT id FROM public.cm_user_profiles 
        WHERE approved = true AND role = ANY(ARRAY['Admin'::text, 'Admin Master'::text, 'CEO'::text])
    )
);

CREATE POLICY "cm_company_targets_delete_auth" 
ON public.cm_company_targets 
FOR DELETE 
TO authenticated 
USING (
    auth.uid() IN (
        SELECT id FROM public.cm_user_profiles 
        WHERE approved = true AND role = 'Admin Master'::text
    )
);

-- 5. Copiar dados legados de ceo_targets para cm_company_targets
INSERT INTO public.cm_company_targets (
    id,
    year,
    month,
    channel,
    target_forecast,
    target_internal,
    target_forecast_qty,
    target_internal_qty,
    created_at,
    updated_at
)
SELECT 
    id,
    year,
    month,
    COALESCE(channel, 'Todos'),
    COALESCE(target_forecast, 0),
    COALESCE(target_internal, 0),
    COALESCE(target_forecast_qty, 0),
    COALESCE(target_internal_qty, 0),
    COALESCE(updated_at, timezone('utc'::text, now())),
    COALESCE(updated_at, timezone('utc'::text, now()))
FROM public.ceo_targets
ON CONFLICT (year, month, channel) DO UPDATE SET
    target_forecast = EXCLUDED.target_forecast,
    target_internal = EXCLUDED.target_internal,
    target_forecast_qty = EXCLUDED.target_forecast_qty,
    target_internal_qty = EXCLUDED.target_internal_qty,
    updated_at = EXCLUDED.updated_at;

-- 6. Sincronizar sequência de identidade
SELECT setval(
    pg_get_serial_sequence('public.cm_company_targets', 'id'),
    COALESCE((SELECT MAX(id) FROM public.cm_company_targets), 1),
    true
);

-- 7. Grants
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cm_company_targets TO authenticated;
GRANT SELECT ON public.cm_company_targets TO anon;
